### ISSUE TITLE
Can we have a serverless mode ?

### ISSUE THREAD

**Issue by riderx** [crisp-im/node-crisp-status-reporter#1]
I would like to add crisp sdk in all my serverless function init and send when it worked or not, but i can't have a service all time up

**Comment by baptistejamin** [comment]
Hey.You should use HTTP monitoring instead of this because serverless means there is a server, just it’s not running 100% of the time Sent from my iPhoneOn 16 Jan 2023, at 08:59, Martin DONADIEU ***@***.***> wrote:﻿
I would like to add crisp sdk in all my serverless function init and send when it worked or not, but i can't have a service all time up

**Comment by valeriansaliou** [comment]
Hey Martin! Glad to see you there :) This library is not designed for serverless, and serverless is unfortunately the kind of things that you cannot really monitor IMHO / don't need to monitor for uptime (as your fn are ran on-demand and there is no active runtime).
